---
jobs:
- name: atomy
  public: true
  plan:
  - aggregate:
    - get: rubinius-image
      trigger: true
    - get: atomy
      trigger: true
      version: every
  - task: tests
    file: atomy/ci/tests.yml
    image: rubinius-image

resources:
- name: rubinius-image
  type: docker-image
  source: {repository: rubinius/docker}

- name: atomy
  type: git
  source:
    uri: https://github.com/vito/atomy
